2021-11-05T00:05:37.3135240+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T00:05:37.3435440+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T00:05:37.4244920+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T00:05:37.4570860+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T00:05:37.4610630+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T00:05:47.4871950+01:00 0HMCVSUEKHJUV:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gruppeoppgave_1.Controllers.OrderController.GetAll() in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/OrderController.cs:line 29
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-11-05T00:05:54.8896500+01:00 0HMCVSUEKHJUV:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gruppeoppgave_1.Controllers.OrderController.GetAll() in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/OrderController.cs:line 29
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-11-05T00:06:15.1823970+01:00 0HMCVSUEKHJUV:00000003 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gruppeoppgave_1.Controllers.OrderController.GetAll() in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/OrderController.cs:line 29
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-11-05T00:15:28.0224160+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T00:15:28.0684270+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T00:15:28.1004790+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T00:15:28.1298530+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T00:15:28.1603060+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T00:17:41.0669690+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T00:17:41.1048040+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T00:17:41.1098000+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T00:17:41.1618750+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T00:17:41.1894060+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T00:17:52.6740240+01:00 0HMCVT56ALEUT:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gruppeoppgave_1.Controllers.OrderController.GetAll() in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/OrderController.cs:line 29
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-11-05T00:18:12.0708130+01:00 0HMCVT56ALEUT:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gruppeoppgave_1.Controllers.CustomerController.GetAll() in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/CustomerController.cs:line 30
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-11-05T00:18:20.4191740+01:00 0HMCVT56ALEUT:00000006 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gruppeoppgave_1.Controllers.OrderController.GetAll() in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/OrderController.cs:line 29
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-11-05T00:21:51.1758870+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T00:21:51.2133440+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T00:21:51.2196560+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T00:21:51.2477020+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T00:21:51.2751150+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T00:29:07.5541350+01:00 0HMCVT7GQV1HB:00000007 [INF] Port with id: '6' not found (28ccce51)
2021-11-05T00:29:59.3459500+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T00:29:59.3671170+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T00:29:59.3757200+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T00:29:59.3995510+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T00:29:59.4235980+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T00:30:29.8643310+01:00 0HMCVTC2CVET7:00000005 [INF] Port with id: '6' updated (52045029)
2021-11-05T01:54:11.0526180+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T01:54:11.1189690+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T01:54:11.1534210+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T01:54:11.1584530+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T01:54:11.1846810+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T01:54:56.5911310+01:00 0HMCVUR3S6TGA:00000006 [INF] Customer with email: lavrans@bjerkestrand.com not found. Creating new customer (54d497ee)
2021-11-05T01:54:56.6856970+01:00 0HMCVUR3S6TGA:00000006 [INF] Order created (9a8736be)
2021-11-05T02:09:09.1979820+01:00 0HMCVUR3S6TGJ:00000004 [INF] Customer with email: asdæ@casød0l.cosd not found. Creating new customer (91dd66df)
2021-11-05T02:09:09.2778380+01:00 0HMCVUR3S6TGJ:00000004 [INF] Order created (9a8736be)
2021-11-05T02:15:39.7383010+01:00 0HMCVUR3S6TGP:00000005 [INF] Customer with email: lavsv@caps.co not found. Creating new customer (9c9fcb5a)
2021-11-05T02:15:39.7827470+01:00 0HMCVUR3S6TGP:00000005 [INF] Order created (9a8736be)
2021-11-05T02:17:22.8834080+01:00 0HMCVUR3S6TGM:00000008 [INF] Customer with email: lavrnas@cso.co not found. Creating new customer (1d771684)
2021-11-05T02:17:22.9152630+01:00 0HMCVUR3S6TGM:00000008 [INF] Order created (9a8736be)
2021-11-05T02:18:44.2728090+01:00 0HMCVUR3S6TGL:0000000B [INF] Customer with email: asdf@casdc.co not found. Creating new customer (4407053e)
2021-11-05T02:18:44.2967990+01:00 0HMCVUR3S6TGL:0000000B [INF] Order created (9a8736be)
2021-11-05T02:19:18.9199980+01:00 0HMCVUR3S6TGL:0000000C [INF] Customer with email: asdf@casdc.co already exists. Assigning order to existing customer and updated customer (7cc6a21b)
2021-11-05T02:19:18.9581830+01:00 0HMCVUR3S6TGL:0000000C [INF] Order created (9a8736be)
2021-11-05T02:20:47.6186050+01:00 0HMCVUR3S6TGO:00000009 [INF] Customer(passenger) with name: Ali Ansar not found. Creating new customer (36b06295)
2021-11-05T02:20:47.6917130+01:00 0HMCVUR3S6TGO:00000009 [INF] Customer with email: lavrans@bjerksrtra.com not found. Creating new customer (6723825e)
2021-11-05T02:20:47.7344890+01:00 0HMCVUR3S6TGO:00000009 [INF] Order created (9a8736be)
2021-11-05T02:23:20.6978800+01:00 0HMCVUR3S6TGM:00000010 [INF] Login for user: admin failed (c5680bc9)
2021-11-05T03:19:41.2557230+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T03:19:41.2988360+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T03:19:41.3082270+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T03:19:41.3137490+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T03:19:41.3237760+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T03:52:43.0567700+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T03:52:43.1218680+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T03:52:43.1515720+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T03:52:43.1551490+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T03:52:43.1576070+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T04:23:43.7215600+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T04:23:43.7636740+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T04:23:43.7960330+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T04:23:43.8002930+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T04:23:43.8272460+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T06:59:16.8796670+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T06:59:16.8913860+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T06:59:16.8963140+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T06:59:16.8998110+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T06:59:16.9285690+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T07:03:12.0575670+01:00 0HMD045JIJJ36:00000001 [ERR] Failed executing DbCommand ("8"ms) [Parameters=["@p0='?'"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"Companies\"
WHERE \"Id\" = @p0;
SELECT changes();" (627a98df)
2021-11-05T07:03:12.2511210+01:00 0HMD045JIJJ36:00000001 [ERR] An exception occurred in the database while saving changes for context type '"Gruppeoppgave_1.Models.DatabaseContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)" (170f029e)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Gruppeoppgave_1.DAL.CompanyRepository.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/DAL/CompanyRepository.cs:line 91
   at Gruppeoppgave_1.Controllers.CompanyController.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/CompanyController.cs:line 142
2021-11-05T07:03:13.0131190+01:00 0HMD045JIJJ36:00000001 [INF] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-11-05T07:07:56.3555940+01:00 0HMD045JIJJ37:00000007 [ERR] Failed executing DbCommand ("8"ms) [Parameters=["@p0='?'"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"Companies\"
WHERE \"Id\" = @p0;
SELECT changes();" (627a98df)
2021-11-05T07:07:56.3928200+01:00 0HMD045JIJJ37:00000007 [ERR] An exception occurred in the database while saving changes for context type '"Gruppeoppgave_1.Models.DatabaseContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)" (170f029e)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Gruppeoppgave_1.DAL.CompanyRepository.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/DAL/CompanyRepository.cs:line 91
2021-11-05T07:07:56.7168410+01:00 0HMD045JIJJ37:00000007 [INF] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-11-05T07:10:32.4100380+01:00 0HMD045JIJJ3C:0000000B [ERR] Failed executing DbCommand ("8"ms) [Parameters=["@p0='?'"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"Companies\"
WHERE \"Id\" = @p0;
SELECT changes();" (627a98df)
2021-11-05T07:10:32.4402550+01:00 0HMD045JIJJ3C:0000000B [ERR] An exception occurred in the database while saving changes for context type '"Gruppeoppgave_1.Models.DatabaseContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)" (170f029e)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Gruppeoppgave_1.DAL.CompanyRepository.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/DAL/CompanyRepository.cs:line 91
   at Gruppeoppgave_1.Controllers.CompanyController.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/CompanyController.cs:line 142
2021-11-05T07:10:32.7318330+01:00 0HMD045JIJJ3C:0000000B [INF] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-11-05T07:12:31.1062770+01:00 0HMD045JIJJ39:0000000C [ERR] Failed executing DbCommand ("3"ms) [Parameters=["@p0='?'"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"Companies\"
WHERE \"Id\" = @p0;
SELECT changes();" (627a98df)
2021-11-05T07:12:31.1522300+01:00 0HMD045JIJJ39:0000000C [ERR] An exception occurred in the database while saving changes for context type '"Gruppeoppgave_1.Models.DatabaseContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)" (170f029e)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Gruppeoppgave_1.DAL.CompanyRepository.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/DAL/CompanyRepository.cs:line 91
   at Gruppeoppgave_1.Controllers.CompanyController.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/CompanyController.cs:line 142
2021-11-05T07:12:31.3692330+01:00 0HMD045JIJJ39:0000000C [INF] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-11-05T07:12:58.5407220+01:00 0HMD045JIJJ3A:0000000D [INF] Company with id: '2' updated (7a1ca346)
2021-11-05T07:13:04.7083970+01:00 0HMD045JIJJ39:00000011 [ERR] Failed executing DbCommand ("2"ms) [Parameters=["@p0='?'"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"Companies\"
WHERE \"Id\" = @p0;
SELECT changes();" (627a98df)
2021-11-05T07:13:04.7350720+01:00 0HMD045JIJJ39:00000011 [ERR] An exception occurred in the database while saving changes for context type '"Gruppeoppgave_1.Models.DatabaseContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)" (170f029e)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Gruppeoppgave_1.DAL.CompanyRepository.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/DAL/CompanyRepository.cs:line 91
   at Gruppeoppgave_1.Controllers.CompanyController.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/CompanyController.cs:line 142
2021-11-05T07:13:05.0356260+01:00 0HMD045JIJJ39:00000011 [INF] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-11-05T07:18:27.9970160+01:00 0HMD045JIJJ3B:00000014 [INF] Customer with id: '1' updated (313f804b)
2021-11-05T07:18:35.0359150+01:00 0HMD045JIJJ3A:00000019 [ERR] Failed executing DbCommand ("5"ms) [Parameters=["@p0='?'"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"Customers\"
WHERE \"Id\" = @p0;
SELECT changes();" (627a98df)
2021-11-05T07:18:35.0838400+01:00 0HMD045JIJJ3A:00000019 [ERR] An exception occurred in the database while saving changes for context type '"Gruppeoppgave_1.Models.DatabaseContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)" (170f029e)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Gruppeoppgave_1.Controllers.CustomerRepository.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/DAL/CustomerRepository.cs:line 114
   at Gruppeoppgave_1.Controllers.CustomerController.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/CustomerController.cs:line 152
2021-11-05T07:18:35.3404010+01:00 0HMD045JIJJ3A:00000019 [INF] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-11-05T07:19:32.1910540+01:00 0HMD045JIJJ3F:00000009 [ERR] Failed executing DbCommand ("4"ms) [Parameters=["@p0='?'"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"Customers\"
WHERE \"Id\" = @p0;
SELECT changes();" (627a98df)
2021-11-05T07:19:32.2206140+01:00 0HMD045JIJJ3F:00000009 [ERR] An exception occurred in the database while saving changes for context type '"Gruppeoppgave_1.Models.DatabaseContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)" (170f029e)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Gruppeoppgave_1.Controllers.CustomerRepository.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/DAL/CustomerRepository.cs:line 114
   at Gruppeoppgave_1.Controllers.CustomerController.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/Controllers/CustomerController.cs:line 152
2021-11-05T07:19:32.4373000+01:00 0HMD045JIJJ3F:00000009 [INF] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-11-05T07:29:36.3101520+01:00 0HMD045JIJJ3K:00000004 [INF] Port with id: '6' updated (52045029)
2021-11-05T07:29:44.5955300+01:00 0HMD045JIJJ3H:0000000A [ERR] Failed executing DbCommand ("3"ms) [Parameters=["@p0='?'"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"Ports\"
WHERE \"Id\" = @p0;
SELECT changes();" (627a98df)
2021-11-05T07:29:44.6100720+01:00 0HMD045JIJJ3H:0000000A [ERR] An exception occurred in the database while saving changes for context type '"Gruppeoppgave_1.Models.DatabaseContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)" (170f029e)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2021-11-05T07:29:44.8336120+01:00 0HMD045JIJJ3H:0000000A [INF] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-11-05T07:30:02.3113480+01:00 0HMD045JIJJ3L:00000006 [INF] Port with name: 'Drammen' created (14f1026f)
2021-11-05T07:30:12.5512500+01:00 0HMD045JIJJ3L:00000007 [INF] Port with name: 'Drammen' already exists (abe77675)
2021-11-05T07:30:49.3500240+01:00 0HMD045JIJJ3L:00000008 [INF] Port with name: 'Drammen' already exists (abe77675)
2021-11-05T07:34:39.0252780+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T07:34:39.1528020+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T07:34:39.1663470+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T07:34:39.1714390+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T07:34:39.1752660+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T07:38:02.4636440+01:00 0HMD04PBR2AKG:00000001 [INF] Port with name: 'Drammen' created (14f1026f)
2021-11-05T07:48:46.8458010+01:00 0HMD04PBR2AKM:00000005 [INF] Port with id: '7' deleted (d4f7fd1a)
2021-11-05T07:49:25.2925830+01:00 0HMD04PBR2AKK:00000009 [ERR] Failed executing DbCommand ("8"ms) [Parameters=["@p0='?'"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"Companies\"
WHERE \"Id\" = @p0;
SELECT changes();" (627a98df)
2021-11-05T07:49:25.4491350+01:00 0HMD04PBR2AKK:00000009 [ERR] An exception occurred in the database while saving changes for context type '"Gruppeoppgave_1.Models.DatabaseContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)" (170f029e)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Gruppeoppgave_1.DAL.CompanyRepository.Delete(Int32 id) in /Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1/DAL/CompanyRepository.cs:line 91
2021-11-05T07:49:25.9452420+01:00 0HMD04PBR2AKK:00000009 [INF] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-11-05T08:35:40.5963120+01:00 0HMD04PBR2AKN:0000000B [INF] Port with id: '1' updated (57d1fcfc)
2021-11-05T09:10:03.1547440+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T09:10:03.2242580+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T09:10:03.2809500+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T09:10:03.2860830+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T09:10:03.2889150+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T09:54:19.2135910+01:00 0HMD06ELREKTD:00000028 [INF] Name is required; Name is required; Name is required (91957b4b)
2021-11-05T09:55:43.5294240+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T09:55:43.5689260+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T09:55:43.5995170+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T09:55:43.6058770+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T09:55:43.6091930+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T10:04:13.8609440+01:00 0HMD0786FE70S:00000004 [INF] Object reference not set to an instance of an object. (f59a5554)
2021-11-05T10:04:58.5459310+01:00 0HMD0786FE70S:00000005 [INF] Object reference not set to an instance of an object. (f59a5554)
2021-11-05T10:06:13.7376790+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T10:06:13.7797830+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T10:06:13.7856280+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T10:06:13.7908640+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T10:06:13.7952460+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T10:06:35.9480400+01:00 0HMD07E2E8USJ:00000003 [INF] Object reference not set to an instance of an object. (f59a5554)
2021-11-05T10:06:43.5708240+01:00 0HMD07E2E8USJ:00000004 [INF] Object reference not set to an instance of an object. (f59a5554)
2021-11-05T10:06:49.9291430+01:00 0HMD07E2E8USJ:00000005 [INF] Object reference not set to an instance of an object. (f59a5554)
2021-11-05T10:08:51.0345530+01:00 0HMD07E2E8USN:00000005 [INF] Object reference not set to an instance of an object. (f59a5554)
2021-11-05T10:09:41.8743920+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T10:09:41.8869630+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T10:09:41.8933110+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T10:09:41.9208810+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T10:09:41.9476640+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T10:10:05.7738730+01:00 0HMD07G0A8BUT:00000008 [INF] Name is required; Name is required; Name is required (91957b4b)
2021-11-05T10:12:21.7117270+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T10:12:21.7543370+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T10:12:21.7694280+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T10:12:21.7734510+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T10:12:21.7765560+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T10:12:51.7628470+01:00 0HMD07HG271QT:00000005 [INF] Route created (9bce946c)
2021-11-05T10:21:38.5753750+01:00 0HMD07HG271R7:00000013 [INF] Route created (9bce946c)
2021-11-05T10:24:52.7568050+01:00 0HMD07HG271R7:0000001B [INF] Route with id: '6' deleted (9ab0e586)
2021-11-05T10:44:53.2975980+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T10:44:53.3411360+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T10:44:53.3777400+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T10:44:53.3835260+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T10:44:53.3892150+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T10:45:47.2184350+01:00 0HMD083LKU4OD:0000000E [INF] Customer with id: '1' updated (313f804b)
2021-11-05T11:11:13.5448780+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T11:11:13.5601900+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T11:11:13.5668530+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T11:11:13.5698480+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T11:11:13.5723780+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T11:34:21.4228410+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T11:34:21.5002730+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T11:34:21.5304610+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T11:34:21.5577150+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T11:34:21.5844990+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T11:35:24.6711640+01:00 0HMD08VA61BJD:0000000B [INF] Unexpected character encountered while parsing value: f. Path 'direction', line 1, position 66.; Unexpected character encountered while parsing value: a. Path 'direction', line 1, position 66. (46fe228a)
2021-11-05T11:38:06.1123100+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T11:38:06.1484370+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T11:38:06.1575530+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T11:38:06.1633720+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T11:38:06.1896730+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T11:38:31.1637460+01:00 0HMD091D8QACQ:00000004 [INF] Origin port is required; Company is required; Destination port is required (89b49a94)
2021-11-05T11:41:08.5767150+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T11:41:08.6170440+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T11:41:08.7024000+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T11:41:08.7316640+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T11:41:08.7615450+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T11:41:44.3733640+01:00 0HMD0933H77GH:00000007 [INF] Unexpected character encountered while parsing value: f. Path 'direction', line 1, position 65.; Unexpected character encountered while parsing value: a. Path 'direction', line 1, position 65. (64a7c588)
2021-11-05T11:45:02.8717680+01:00 0HMD0933H77GO:00000009 [INF] Origin port is required; Company is required; Destination port is required (89b49a94)
2021-11-05T11:46:43.4160960+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T11:46:43.4532690+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T11:46:43.4832690+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T11:46:43.5111660+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T11:46:43.5140590+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T11:47:19.5122510+01:00 0HMD09678OEKR:0000000B [INF] Error converting value {null} to type 'System.Int32'. Path 'direction', line 1, position 67. (ce27cffa)
2021-11-05T11:48:57.5036020+01:00 0HMD09678OEKU:0000000E [INF] Destination port is required (7fffd680)
2021-11-05T11:49:29.4168500+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T11:49:29.4615040+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T11:49:29.4974510+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T11:49:29.5303020+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T11:49:29.5559060+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T11:50:11.7925220+01:00 0HMD097OQCSI6:0000000B [INF] Error converting value {null} to type 'System.Int32'. Path 'direction', line 1, position 66. (e470792b)
2021-11-05T11:52:29.6277610+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2021-11-05T11:52:29.6883610+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2021-11-05T11:52:29.7177830+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-05T11:52:29.7717640+01:00  [INF] Hosting environment: "Development" (c3307c92)
2021-11-05T11:52:29.7974170+01:00  [INF] Content root path: "/Users/lavransbjerkestrand/OneDrive - OsloMet/ITPE3200 - Webutvikling/Gruppeoppgave-1/Gruppeoppgave-1" (b5d60022)
2021-11-05T11:52:33.2924550+01:00 0HMD099EG63A3:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

Gruppeoppgave_1.Controllers.RouteTimeController.GetByRouteId (Gruppeoppgave-1)
Gruppeoppgave_1.Controllers.RouteTimeController.GetById (Gruppeoppgave-1)
Fallback {*path:nonfile}
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
